# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

RCPPlnlOFdelta <- function(delta, N, T, W, Y, Ztilde, Xawith1) {
    .Call(`_QuantileDSAR_RCPPlnlOFdelta`, delta, N, T, W, Y, Ztilde, Xawith1)
}

f_zeta_hat <- function(N, T, W, Y, Ztilde, Xawith1, deltahat) {
    .Call(`_QuantileDSAR_f_zeta_hat`, N, T, W, Y, Ztilde, Xawith1, deltahat)
}

f_score_b <- function(indicatorb, N, T, p, q, W, Y, Ztilde, Xawith1, zetahat, Vhat) {
    .Call(`_QuantileDSAR_f_score_b`, indicatorb, N, T, p, q, W, Y, Ztilde, Xawith1, zetahat, Vhat)
}

f_CovM_QMLE <- function(Bnum, N, T, p, q, W, Y, Ztilde, Xawith1, zetahat, Vhat) {
    .Call(`_QuantileDSAR_f_CovM_QMLE`, Bnum, N, T, p, q, W, Y, Ztilde, Xawith1, zetahat, Vhat)
}

f_CovM_secbetacheck <- function(p, q, zetahat, CovMzetahat) {
    .Call(`_QuantileDSAR_f_CovM_secbetacheck`, p, q, zetahat, CovMzetahat)
}

f_V_hat <- function(zetahat, N, T, W, Y, Ztilde) {
    .Call(`_QuantileDSAR_f_V_hat`, zetahat, N, T, W, Y, Ztilde)
}

f_vartheta_hat <- function(Vhat, N, T) {
    .Call(`_QuantileDSAR_f_vartheta_hat`, Vhat, N, T)
}

wqrLF <- function(varphi, N, y, xwith1, tau, weights) {
    .Call(`_QuantileDSAR_wqrLF`, varphi, N, y, xwith1, tau, weights)
}

gr_wqrLF <- function(varphi, N, y, xwith1, tau, weights) {
    .Call(`_QuantileDSAR_gr_wqrLF`, varphi, N, y, xwith1, tau, weights)
}

f_WCQE_tausM <- function(p, N, y, x, xwith1, tausNUM, tausV, weightsV) {
    .Call(`_QuantileDSAR_f_WCQE_tausM`, p, N, y, x, xwith1, tausNUM, tausV, weightsV)
}

f_betac_tilde <- function(varphitautildeM) {
    .Call(`_QuantileDSAR_f_betac_tilde`, varphitautildeM)
}

f_weights_rq <- function(N, Xawith1, betactilde) {
    .Call(`_QuantileDSAR_f_weights_rq`, N, Xawith1, betactilde)
}

f_eta_est <- function(N, Xawith1, varthetahat, betaest) {
    .Call(`_QuantileDSAR_f_eta_est`, N, Xawith1, varthetahat, betaest)
}

f_feta_tildeV <- function(xV, N, Xawith1, varthetahat, betactilde) {
    .Call(`_QuantileDSAR_f_feta_tildeV`, xV, N, Xawith1, varthetahat, betactilde)
}

f_D_est <- function(N, Xawith1, betaest) {
    .Call(`_QuantileDSAR_f_D_est`, N, Xawith1, betaest)
}

f_ASD_WCQE <- function(tauseq, XitauseqtildeV, Dtilde, N, p) {
    .Call(`_QuantileDSAR_f_ASD_WCQE`, tauseq, XitauseqtildeV, Dtilde, N, p)
}

f_H_est <- function(K, tauK, XitauKestV) {
    .Call(`_QuantileDSAR_f_H_est`, K, tauK, XitauKestV)
}

f_WQAE <- function(varphitauKhatM, qest, Hest) {
    .Call(`_QuantileDSAR_f_WQAE`, varphitauKhatM, qest, Hest)
}

f_ASD_WQAE <- function(N, qest, Hest, Dhat) {
    .Call(`_QuantileDSAR_f_ASD_WQAE`, N, qest, Hest, Dhat)
}

