# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

f_D_est <- function(N, Xawith1, beta_est) {
    .Call(`_QuantileDSAR_f_D_est`, N, Xawith1, beta_est)
}

f_ASD_varphi <- function(tauseq, N, Xawith1, varthetahat, betactilde, varphitauhatM, Dtilde) {
    .Call(`_QuantileDSAR_f_ASD_varphi`, tauseq, N, Xawith1, varthetahat, betactilde, varphitauhatM, Dtilde)
}

f_ASD_beta <- function(tauK, N, T, Xawith1, varthetahat, betahat, varphitauKhatM, Dhat) {
    .Call(`_QuantileDSAR_f_ASD_beta`, tauK, N, T, Xawith1, varthetahat, betahat, varphitauKhatM, Dhat)
}

f_score_b <- function(b, indicatorb, N, T, p, q, W, Y, Ztilde, Xawith1, zetahat) {
    .Call(`_QuantileDSAR_f_score_b`, b, indicatorb, N, T, p, q, W, Y, Ztilde, Xawith1, zetahat)
}

f_ASD_zeta <- function(Bnum, scoreBnum, N, T, p, q, W, Y, Ztilde, Xawith1, zetahat) {
    .Call(`_QuantileDSAR_f_ASD_zeta`, Bnum, scoreBnum, N, T, p, q, W, Y, Ztilde, Xawith1, zetahat)
}

f_zeta_hat <- function(N, T, W, Y, Ztilde, Xawith1, deltahat) {
    .Call(`_QuantileDSAR_f_zeta_hat`, N, T, W, Y, Ztilde, Xawith1, deltahat)
}

f_vartheta_hat <- function(zetahat, N, T, W, Y, Ztilde) {
    .Call(`_QuantileDSAR_f_vartheta_hat`, zetahat, N, T, W, Y, Ztilde)
}

f_betac_tilde <- function(varphitautildeM) {
    .Call(`_QuantileDSAR_f_betac_tilde`, varphitautildeM)
}

f_weights_rq <- function(N, Xawith1, betactilde) {
    .Call(`_QuantileDSAR_f_weights_rq`, N, Xawith1, betactilde)
}

wqrLF <- function(varphi, N, y, x, tau, weights) {
    .Call(`_QuantileDSAR_wqrLF`, varphi, N, y, x, tau, weights)
}

f_beta_hat <- function(tauK, N, Xawith1, varthetahat, betactilde, varphitauKhatM) {
    .Call(`_QuantileDSAR_f_beta_hat`, tauK, N, Xawith1, varthetahat, betactilde, varphitauKhatM)
}

RCPPlnlOFdelta <- function(delta, N, T, W, Y, Ztilde, Xawith1) {
    .Call(`_QuantileDSAR_RCPPlnlOFdelta`, delta, N, T, W, Y, Ztilde, Xawith1)
}

